export const endpoints = {
  health: '/health',

  auth: {
    login:           '/auth/login',
    refresh:         '/auth/refresh',
    logout:          '/auth/logout',
    me:              '/auth/me',
    changePassword:  '/auth/change-password',
    resetRequest:    '/auth/password-reset/request',
    resetComplete:   '/auth/password-reset/complete',
    users:           '/auth/users',
    user:            (id: string) => `/auth/users/${id}`,
    deactivateUser:  (id: string) => `/auth/users/${id}/deactivate`,
    activateUser:    (id: string) => `/auth/users/${id}/activate`,
    changeRole:      (id: string) => `/auth/users/${id}/role`,
    unlockUser:      (id: string) => `/auth/users/${id}/unlock`,
    resetUserPw:     (id: string) => `/auth/users/${id}/reset-password`,
    inviteUser:      (id: string) => `/auth/users/${id}/invite`,
  },

  // ── Students ──────────────────────────────────────────────────────────────
  students: {
    list:                   '/students',
    create:                 '/students',
    byRegistration:         (reg: string) => `/students/registration/${reg}`,
    one:                    (id: string) => `/students/${id}`,
    update:                 (id: string) => `/students/${id}`,
    updateStatus:           (id: string) => `/students/${id}/status`,
    promote:                (id: string) => `/students/${id}/promote`,
    bulkPromote:            '/students/promotions/bulk',
    guardians:              (id: string) => `/students/${id}/guardians`,
    addGuardian:            (id: string) => `/students/${id}/guardians`,
    updateGuardian:         (id: string, gId: string) => `/students/${id}/guardians/${gId}`,
    removeGuardian:         (id: string, gId: string) => `/students/${id}/guardians/${gId}`,

    attendance:             '/students/attendance',
    attendanceList:         '/students/attendance',
    attendanceSummary:      (id: string) => `/students/attendance/summary/${id}`,

    discipline:             '/students/discipline',
    disciplineList:         '/students/discipline',
    disciplineByStudent:    (id: string) => `/students/discipline/${id}`,
    disciplineResolve:      (recordId: string) => `/students/discipline/${recordId}/resolve`,

    classes:                '/students/classes',
    createClass:            '/students/classes',
    updateClass:            (id: string) => `/students/classes/${id}`,
    classStudents:          (id: string) => `/students/classes/${id}/students`,
    classPathways:          '/students/class-pathways',
    createPathway:          '/students/class-pathways',
    resolvePathway:         '/students/class-pathways/resolve',

    academicYears:          '/students/academic-years',
    createAcademicYear:     '/students/academic-years',
    terms:                  '/students/terms',
    createTerm:             '/students/terms',

    perfAlerts:             '/students/performance/alerts',
    perfAlertsByClass:      (id: string) => `/students/performance/alerts/class/${id}`,
    perfAlertResolve:       (id: string) => `/students/performance/alerts/${id}/resolve`,
    perfPairings:           '/students/performance/pairings',
    perfPairingStatus:      (id: string) => `/students/performance/pairings/${id}/status`,
    perfCreatePairing:      '/students/performance/pairings',
    perfEngineRun:          '/students/performance/engine/run',
    perfEngineConfig:       '/students/performance/engine/config',
    perfSummaryClass:       (id: string) => `/students/performance/summary/class/${id}`,
    perfSummarySchool:      '/students/performance/summary/school',
    perfPairingEffect:      '/students/performance/pairings/effectiveness',
    perfStudent:            (id: string) => `/students/performance/${id}`,
    perfStudentSubject:     (sId: string, subId: string) => `/students/performance/${sId}/subject/${subId}`,
  },

  // ── Academics ─────────────────────────────────────────────────────────────
  academics: {
    subjects:                '/academics/subjects',
    createSubject:           '/academics/subjects',
    updateSubject:           (id: string) => `/academics/subjects/${id}`,

    classSubjects:           '/academics/class-subjects',
    createClassSubject:      '/academics/class-subjects',
    updateClassSubject:      (id: string) => `/academics/class-subjects/${id}`,

    combinations:            '/academics/subject-combinations',
    createCombination:       '/academics/subject-combinations',
    updateCombination:       (id: string) => `/academics/subject-combinations/${id}`,
    deleteCombination:       (id: string) => `/academics/subject-combinations/${id}`,

    studentEnrollments:      '/academics/student-subject-enrollments',
    bulkEnroll:              '/academics/student-subject-enrollments/bulk-combination',
    updateEnrollment:        (id: string) => `/academics/student-subject-enrollments/${id}`,
    deleteEnrollment:        (id: string) => `/academics/student-subject-enrollments/${id}`,

    gradingScales:           '/academics/grading-scales',
    activateScale:           (id: string) => `/academics/grading-scales/${id}/activate`,
    assessmentTypes:         '/academics/assessment-types',
    createAssessmentType:    '/academics/assessment-types',

    generateAssessments:     '/academics/assessments/generate',
    assessments:             '/academics/assessments',
    pendingApproval:         '/academics/assessments/pending-approval',
    assessment:              (id: string) => `/academics/assessments/${id}`,
    marksSheet:              (id: string) => `/academics/assessments/${id}/marks/sheet`,
    bulkMarks:               (id: string) => `/academics/assessments/${id}/marks/bulk`,
    updateMark:              (id: string, mId: string) => `/academics/assessments/${id}/marks/${mId}`,
    submitAssessment:        (id: string) => `/academics/assessments/${id}/submit`,
    marksReview:             (id: string) => `/academics/assessments/${id}/marks/review`,
    approveAssessment:       (id: string) => `/academics/assessments/${id}/approve`,
    rejectAssessment:        (id: string) => `/academics/assessments/${id}/reject`,

    results:                 '/academics/results',
    classTermResults:        (cId: string, tId: string) => `/academics/results/class/${cId}/term/${tId}`,
    publishResults:          '/academics/results/publish',

    generateReportCards:     '/academics/report-cards/generate',
    reportCard:              (sId: string, tId: string) => `/academics/report-cards/${sId}/term/${tId}`,
    reportCardPdf:           (sId: string, tId: string) => `/academics/report-cards/${sId}/term/${tId}/pdf`,
    updateComments:          (id: string) => `/academics/report-cards/${id}/comments`,

    timetables:              '/academics/timetables',
    deleteTimetable:         (id: string) => `/academics/timetables/${id}`,

    syllabus:                '/academics/syllabus',
    updateSyllabus:          (id: string) => `/academics/syllabus/${id}`,

    perfAlerts:              '/academics/performance/alerts',
    perfAlertsByClass:       (id: string) => `/academics/performance/alerts/class/${id}`,
    perfAlertResolve:        (id: string) => `/academics/performance/alerts/${id}/resolve`,
    perfAlertEscalate:       (id: string) => `/academics/performance/alerts/${id}/escalate`,
    perfPairings:            '/academics/performance/pairings',
    perfPairingActivate:     (id: string) => `/academics/performance/pairings/${id}/activate`,
    perfPairingReject:       (id: string) => `/academics/performance/pairings/${id}/reject`,
    perfPairingCreate:       '/academics/performance/pairings',
    perfPairingEffect:       '/academics/performance/pairings/effectiveness',
    perfStudent:             (id: string) => `/academics/performance/student/${id}`,
    perfClassSummary:        (id: string) => `/academics/performance/class/${id}/summary`,
    perfSchoolSummary:       '/academics/performance/school/summary',
    perfEngineRun:           '/academics/performance/engine/run',
    perfEngineConfig:        '/academics/performance/engine/config',

    interventions:           '/academics/interventions',
    createIntervention:      '/academics/interventions',
    updateIntervention:      (id: string) => `/academics/interventions/${id}`,
    studentInterventions:    (id: string) => `/academics/interventions/student/${id}`,
  },

  // ── Finance ───────────────────────────────────────────────────────────────
  finance: {
    feeCategories:           '/finance/fee-categories',
    createFeeCategory:       '/finance/fee-categories',
    updateFeeCategory:       (id: string) => `/finance/fee-categories/${id}`,
    deleteFeeCategory:       (id: string) => `/finance/fee-categories/${id}`,

    feeStructures:           '/finance/fee-structures',
    feeMatrix:               '/finance/fee-structures/matrix',
    updateFeeStructure:      (id: string) => `/finance/fee-structures/${id}`,
    deactivateFeeStructure:  (id: string) => `/finance/fee-structures/${id}/deactivate`,
    studentGroups:           '/finance/fee-structures/student-groups',
    studentGroupMemberships: '/finance/fee-structures/student-groups/memberships',
    removeMembership:        (id: string) => `/finance/fee-structures/student-groups/memberships/${id}/remove`,

    bulkFeeAssignments:      '/finance/fee-assignments/bulk',
    feeAssignmentByStudent:  (id: string) => `/finance/fee-assignments/${id}`,
    feeAssignments:          '/finance/fee-assignments',
    deleteFeeAssignment:     (id: string) => `/finance/fee-assignments/${id}`,

    generateInvoices:        '/finance/invoices/generate',
    invoices:                '/finance/invoices',
    invoiceJob:              (id: string) => `/finance/invoices/jobs/${id}`,
    invoice:                 (id: string) => `/finance/invoices/${id}`,
    studentInvoices:         (id: string) => `/finance/invoices/student/${id}`,
    invoiceDiscount:         (id: string) => `/finance/invoices/${id}/discount`,
    invoiceCancel:           (id: string) => `/finance/invoices/${id}/cancel`,
    invoiceWaive:            (id: string) => `/finance/invoices/${id}/waive`,
    invoicePdf:              (id: string) => `/finance/invoices/${id}/pdf`,

    bankTransfer:            '/finance/payments/bank-transfer',
    cashPayment:             '/finance/payments/cash',
    payments:                '/finance/payments',
    pendingApprovals:        '/finance/payments/pending-approval',
    approvePayment:          (id: string) => `/finance/payments/approvals/${id}/approve`,
    rejectPayment:           (id: string) => `/finance/payments/approvals/${id}/reject`,
    refundPayment:           (id: string) => `/finance/payments/${id}/refund`,

    receipts:                '/finance/receipts',
    receipt:                 (id: string) => `/finance/receipts/${id}`,
    receiptPdf:              (id: string) => `/finance/receipts/${id}/pdf`,
    voidReceipt:             (id: string) => `/finance/receipts/${id}/void`,

    collectionSummary:       '/finance/reports/collection-summary',
    outstandingBalances:     '/finance/reports/outstanding-balances',
    dailyCollections:        '/finance/reports/daily-collections',
    studentStatement:        (id: string) => `/finance/reports/student-statement/${id}`,
    feeDefaulters:           '/finance/reports/fee-defaulters',

    assets:                  '/finance/assets',
    assetSummary:            '/finance/assets/summary',
    asset:                   (id: string) => `/finance/assets/${id}`,
    disposeAsset:            (id: string) => `/finance/assets/${id}/dispose`,

    auditLogs:               '/finance/audit-logs',
  },

  // ── Notifications ─────────────────────────────────────────────────────────
  notifications: {
    list:                    '/notifications',
    unreadCount:             '/notifications/unread-count',
    read:                    (id: string) => `/notifications/${id}/read`,
    readAll:                 '/notifications/read-all',
    delete:                  (id: string) => `/notifications/${id}`,
    announcements:           '/notifications/announcements',
    activeAnnouncements:     '/notifications/announcements/active',
    createAnnouncement:      '/notifications/announcements',
    updateAnnouncement:      (id: string) => `/notifications/announcements/${id}`,
    cancelAnnouncement:      (id: string) => `/notifications/announcements/${id}/cancel`,
    preferences:             '/notifications/preferences',
    templates:               '/notifications/templates',
    template:                (id: string) => `/notifications/templates/${id}`,
    updateTemplate:          (id: string) => `/notifications/templates/${id}`,
    previewTemplate:         '/notifications/templates/preview',
    logs:                    '/notifications/logs',
    stats:                   '/notifications/stats',
    sendManual:              '/notifications/send-manual',
  },

  // ── Analytics ─────────────────────────────────────────────────────────────
  analytics: {
    overview:                '/analytics/overview',
    enrolment:               '/analytics/enrolment',
    enrolmentTrends:         '/analytics/enrolment/trends/chart',
    academicOverview:        '/analytics/academic/overview',
    academicSubject:         (id: string) => `/analytics/academic/subject/${id}`,
    academicTeacher:         (id: string) => `/analytics/academic/teacher/${id}`,
    academicClass:           (id: string) => `/analytics/academic/class/${id}`,
    performanceEngine:       '/analytics/academic/performance-engine',
    financeOverview:         '/analytics/finance/overview',
    financeRevenueForecast:  '/analytics/finance/revenue-forecast',
    financeAssets:           '/analytics/finance/assets-summary',
    attendanceOverview:      '/analytics/attendance/overview',
    attendanceStudent:       (id: string) => `/analytics/attendance/student/${id}`,
    department:              (id: string) => `/analytics/department/${id}`,
    executiveBoard:          '/analytics/executive/board',
    students:                '/analytics/students',
    studentsAtRisk:          '/analytics/students/at-risk',
    topPerformers:           '/analytics/students/top-performers',
    mostImproved:            '/analytics/students/most-improved',
    studentProfile:          (id: string) => `/analytics/students/${id}`,
    generateReport:          '/analytics/reports/generate',
    reports:                 '/analytics/reports',
    report:                  (id: string) => `/analytics/reports/${id}`,
    reportDownload:          (id: string) => `/analytics/reports/${id}/download`,
  },

  // ── Gateway / Operations ─────────────────────────────────────────────────
  gateway: {
    search:                  '/search',
    reportsCatalog:          '/reports/catalog',
    reportsJobs:             '/reports/jobs',
    reportJob:               (id: string) => `/reports/jobs/${id}`,
    reportJobDownload:       (id: string) => `/reports/jobs/${id}/download`,
    reportsDownloads:        '/reports/downloads',
    reportsTemplates:        '/reports/templates',
    reportsScheduled:        '/reports/scheduled',
    reportsAudit:            '/reports/audit',
    resultsPublishReadiness: '/reports/results-publishing/readiness',

    teacherDashboard:        '/teacher/dashboard',
    teacherClassAnalytics:   (id: string) => `/teacher/classes/${id}/analytics`,
    hodDashboard:            '/hod/dashboard',
    hodTeacherPerformance:   '/hod/teachers/performance',
    hodTeacherDetail:        (id: string) => `/hod/teachers/${id}/performance`,
    hodApprovalHistory:      '/hod/approvals/history',
    aqaDashboard:            '/aqa/dashboard',
    aqaEngineRuns:           '/aqa/performance/engine/runs',
    aqaHeatmap:              '/aqa/analytics/heatmap',
    financeDashboard:        '/finance/dashboard',
    principalDashboard:      '/principal/dashboard',
    principalStaff:          '/principal/staff',
    principalStudentProfile: (id: string) => `/principal/students/${id}/profile`,
    principalSchoolSettings: '/principal/settings/school',
    principalAudit:          '/principal/audit',
    hodAudit:                '/hod/audit',
    aqaAudit:                '/aqa/audit',
    adminDashboard:          '/admin/dashboard',
    adminSystemAudit:        '/admin/audit/system',
    adminSettings:           '/admin/system/settings',
    adminFeatureFlags:       '/admin/system/feature-flags',
    adminHealth:             '/admin/system/health',

    exportCreate:            (role: string) => `/${role}/exports`,
    exportDownload:          (role: string, id: string) => `/${role}/exports/${id}/download`,
  },
} as const;
