import { createBrowserRouter } from 'react-router-dom';
import { AppShell } from '../components/layout/AppShell';
import { PublicShell } from '../components/layout/PublicShell';
import { AuthCallbackPage } from '../features/auth/AuthCallbackPage';
import { ForgotPasswordPage } from '../features/auth/ForgotPasswordPage';
import { LoginPage } from '../features/auth/LoginPage';
import { ResetPasswordPage } from '../features/auth/ResetPasswordPage';
import { AboutPage } from '../features/common/AboutPage';
import { AnnouncementDetailPage } from '../features/common/AnnouncementDetailPage';
import { AnnouncementsPage } from '../features/common/AnnouncementsPage';
import { AppErrorPage, ForbiddenPage, NotFoundPage } from '../features/common/ErrorPages';
import { GlobalSearchPage } from '../features/common/GlobalSearchPage';
import { HelpPage } from '../features/common/HelpPage';
import { NotificationDetailPage } from '../features/common/NotificationDetailPage';
import { NotificationsPage } from '../features/common/NotificationsPage';
import { ProfilePage } from '../features/common/ProfilePage';
import { SecurityPage } from '../features/common/SecurityPage';
import { SettingsPage } from '../features/common/SettingsPage';
import {
  AssetDetailPage,
  AssetsListPage,
  CollectionSummaryReportPage,
  CreateAssetPage,
  CreateFeeCategoryPage,
  CreateFeeStructurePage,
  DailyCollectionsReportPage,
  EditAssetPage,
  EditFeeCategoryPage,
  FeeAssignmentsPage,
  FeeCategoriesPage,
  FeeDefaultersReportPage,
  FeeMatrixPage,
  FeeStructuresPage,
  FinanceExportsPage,
  FinanceHomePage,
  FinancialAuditLogPage,
  FinancialReportsPage,
  GenerateInvoicesPage,
  InvoiceDetailPage,
  InvoiceListPage,
  OutstandingBalancesReportPage,
  PaymentDetailPage,
  PaymentListPage,
  PendingPaymentApprovalsPage,
  ReceiptDetailPage,
  ReceiptListPage,
  RecordBankTransferPage,
  RecordCashPaymentPage,
} from '../features/finance/pages/FinancePages';
import { LandingPage } from '../features/public/LandingPage';
import { StatusPage } from '../features/public/StatusPage';
import {
  AcademicSetupHubPage,
  AdminAnalyticsPage,
  AdminAnnouncementsPage,
  AdminFeeCategoriesPage,
  AdminHomePage,
  AdminReportDetailPage,
  AdminReportsPage,
  AdminUsersPage,
  AssessmentTypesPage,
  ClassesPage,
  ClassDetailPage as AdminClassDetailPage,
  CreateGradingScalePage,
  CreateUserPage,
  EditUserPage,
  EnrolStudentPage,
  FinanceAuditAdminPage,
  GradingPage,
  NotificationLogsPage,
  NotificationTemplateDetailPage,
  NotificationTemplatesPage,
  PerformanceEngineAdminPage,
  SendManualNotificationPage,
  StudentAdminProfilePage,
  StudentsPage,
  SubjectDetailPage as AdminSubjectDetailPage,
  SubjectsPage,
  SystemAuditPage,
  SystemSettingsPage,
  UserDetailPage,
} from '../features/admin/pages/AdminPages';
import {
  AcademicAnalyticsOpsPage,
  AnalyticsWorkspacePage,
  BulkMarksSheetPage,
  BulkMarksWorkspacePage,
  ClassAnalyticsDetailPage as OpsClassAnalyticsDetailPage,
  ClassResultsReviewPage,
  ClassTimetablePage,
  CreateTimetableEntryPage,
  DownloadCenterPage,
  EnrolmentAnalyticsPage,
  FinanceAnalyticsOpsPage,
  FinanceReportPage,
  MarksReviewWorkspacePage,
  ReportAccessAuditPage,
  ReportBuilderPage,
  ReportCardGenerationCenterPage,
  ReportCardPreviewPage,
  ReportJobDetailPage,
  ReportJobsPage,
  ReportsHomePage,
  ReportTemplatesPage,
  ResultsPublishingSupportPage,
  ResultsWorkspacePage,
  ScheduledReportsPage,
  StudentAnalyticsDirectoryPage,
  StudentAnalyticsProfilePage,
  StudentStatementReportPage,
  SubjectAnalyticsDetailPage,
  TeacherAnalyticsDetailPage,
  TeacherTimetablePage,
  TimetableWorkspacePage,
} from '../features/operations/pages/OperationsPages';
import {
  CreatePrincipalAnnouncementPage,
  DisciplineOverviewPage,
  FinanceOversightPage,
  MarksFinalApprovalPage,
  PaymentApprovalDetailPage,
  PaymentApprovalsPage,
  PrincipalAnalyticsPage,
  PrincipalAnnouncementsPage,
  PrincipalAuditPage,
  PrincipalExportsPage,
  PrincipalHomePage,
  PrincipalInvoiceManagementPage,
  PrincipalMarksReviewPage,
  PrincipalReportCardDetailPage,
  PrincipalReportsPage,
  PrincipalStudentProfilePage,
  PrincipalStudentsPage,
  PrincipalPerformanceOverviewPage,
  ReportCardsManagementPage,
  ResultsPublishingPage,
  SchoolSettingsPage,
  StaffOverviewPage,
} from '../features/principal/pages/PrincipalPages';
import {
  AcademicAnalyticsPage,
  AqaAlertDetailPage,
  AqaAnnouncementsPage,
  AqaAuditPage,
  AqaClassAnalyticsPage,
  AqaExportsPage,
  AqaHomePage,
  AqaInterventionsPage,
  AqaReportsPage,
  AqaStudentProfilePage,
  AtRiskStudentsPage,
  CreateAqaAnnouncementPage,
  EngineConfigPage,
  EngineControlPage,
  PairingsOverviewPage,
  PerformanceCommandCenterPage,
} from '../features/aqa/pages/AqaPages';
import {
  ApprovalHistoryPage,
  CreateHodAnnouncementPage,
  DepartmentAlertsPage,
  DepartmentOverviewPage,
  DepartmentPairingsPage,
  HodAnnouncementsPage,
  HodAuditPage,
  HodExportsPage,
  HodHomePage,
  HodInterventionsPage,
  HodStudentPerformancePage,
  MarksApprovalReviewPage,
  PendingApprovalsPage,
  SubjectDetailPage,
  TeacherDetailPage,
  TeacherPerformanceListPage,
} from '../features/hod/pages/HodPages';
import {
  AlertDetailPage,
  AssessmentListPage,
  AssessmentSubmitPage,
  AttendanceHistoryPage,
  AttendancePage,
  ClassAnalyticsPage,
  ClassStudentsPage,
  ClassWorkspacePage,
  CreateInterventionPage,
  CreateTeacherAnnouncementPage,
  MarksEntryPage,
  MarksReviewPage,
  PeerPairingsPage,
  PairingDetailPage,
  PerformanceAlertsPage,
  StudentPerformancePage,
  SyllabusPage,
  TeacherAnnouncementsPage,
  TeacherClassesPage,
  TeacherExportsPage,
  TeacherHomePage,
  TimetablePage,
} from '../features/teacher/pages/TeacherPages';
import {
  AdminElearningPage,
  AssignmentDetailPage,
  AqaElearningAuditPage,
  AssignmentsPage,
  CourseCommunicationPage,
  CourseBuilderPage,
  CourseEngagementPage,
  HodCourseDetailPage,
  HodElearningOverviewPage,
  LessonEditorPage,
  LessonPlannerPage,
  ManualMarkingPage,
  MaterialStudioPage,
  PrincipalElearningPage,
  QuizBuilderPage,
  QuizResultsPage,
  SubmissionGradingDeskPage,
  SubmissionsGradingPage,
  TeacherCoursesPage,
} from '../features/elearning';
import { ProtectedRoute } from './ProtectedRoute';
import { RoleRedirect } from './roleRedirect';

export const router = createBrowserRouter([
  {
    element: <PublicShell />,
    errorElement: <AppErrorPage />,
    children: [
      { path: '/', element: <LandingPage /> },
      { path: '/login', element: <LoginPage /> },
      { path: '/forgot-password', element: <ForgotPasswordPage /> },
      { path: '/reset-password', element: <ResetPasswordPage /> },
      { path: '/auth/callback', element: <AuthCallbackPage /> },
      { path: '/status', element: <StatusPage /> },
    ],
  },
  {
    element: (
      <ProtectedRoute>
        <AppShell />
      </ProtectedRoute>
    ),
    errorElement: <AppErrorPage />,
    children: [
      { path: '/app', element: <RoleRedirect /> },
      { path: '/app/mobile-guidance', element: <RoleRedirect /> },
      { path: '/app/profile', element: <ProfilePage /> },
      { path: '/app/settings', element: <SettingsPage /> },
      { path: '/app/security', element: <SecurityPage /> },
      { path: '/app/notifications', element: <NotificationsPage /> },
      { path: '/app/notifications/:id', element: <NotificationDetailPage /> },
      { path: '/app/announcements', element: <AnnouncementsPage /> },
      { path: '/app/announcements/:id', element: <AnnouncementDetailPage /> },
      { path: '/app/search', element: <GlobalSearchPage /> },
      { path: '/app/help', element: <HelpPage /> },
      { path: '/app/about', element: <AboutPage /> },
      { path: '/app/403', element: <ForbiddenPage /> },
      { path: '/app/404', element: <NotFoundPage /> },
      { path: '/app/error', element: <AppErrorPage /> },
      { path: '/teacher', element: <TeacherHomePage /> },
      { path: '/teacher/classes', element: <TeacherClassesPage /> },
      { path: '/teacher/classes/:classSubjectId/students', element: <ClassStudentsPage /> },
      { path: '/teacher/classes/:classSubjectId/analytics', element: <ClassAnalyticsPage /> },
      { path: '/teacher/classes/:classSubjectId', element: <ClassWorkspacePage /> },
      { path: '/teacher/assessments', element: <AssessmentListPage /> },
      { path: '/teacher/assessments/:assessmentId/marks', element: <MarksEntryPage /> },
      { path: '/teacher/assessments/:assessmentId/submit', element: <AssessmentSubmitPage /> },
      { path: '/teacher/assessments/:assessmentId/review', element: <MarksReviewPage /> },
      { path: '/teacher/attendance', element: <AttendancePage /> },
      { path: '/teacher/attendance/history', element: <AttendanceHistoryPage /> },
      { path: '/teacher/performance/alerts', element: <PerformanceAlertsPage /> },
      { path: '/teacher/performance/alerts/:id', element: <AlertDetailPage /> },
      { path: '/teacher/performance/pairings', element: <PeerPairingsPage /> },
      { path: '/teacher/performance/pairings/:id', element: <PairingDetailPage /> },
      { path: '/teacher/students/:studentId/performance', element: <StudentPerformancePage /> },
      { path: '/teacher/timetable', element: <TimetablePage /> },
      { path: '/teacher/syllabus', element: <SyllabusPage /> },
      { path: '/teacher/announcements', element: <TeacherAnnouncementsPage /> },
      { path: '/teacher/announcements/create', element: <CreateTeacherAnnouncementPage /> },
      { path: '/teacher/interventions/create', element: <CreateInterventionPage /> },
      { path: '/teacher/exports', element: <TeacherExportsPage /> },
      { path: '/teacher/elearning', element: <TeacherCoursesPage /> },
      { path: '/teacher/elearning/courses/new', element: <CourseBuilderPage /> },
      { path: '/teacher/elearning/courses/:courseId/overview', element: <CourseBuilderPage /> },
      { path: '/teacher/elearning/courses/:courseId/lessons', element: <LessonPlannerPage /> },
      { path: '/teacher/elearning/courses/:courseId/lessons/new', element: <LessonEditorPage /> },
      { path: '/teacher/elearning/courses/:courseId/lessons/:lessonId/materials/new', element: <MaterialStudioPage /> },
      { path: '/teacher/elearning/courses/:courseId/materials/:materialId/edit', element: <MaterialStudioPage /> },
      { path: '/teacher/elearning/courses/:courseId/assignments/new', element: <AssignmentsPage /> },
      { path: '/teacher/elearning/courses/:courseId/assignments/:assignmentId/submissions/:submissionId/grade', element: <SubmissionGradingDeskPage /> },
      { path: '/teacher/elearning/courses/:courseId', element: <CourseBuilderPage /> },
      { path: '/teacher/elearning/courses/:courseId/lessons/:lessonId', element: <LessonEditorPage /> },
      { path: '/teacher/elearning/courses/:courseId/assignments', element: <AssignmentsPage /> },
      { path: '/teacher/elearning/courses/:courseId/assignments/:assignmentId', element: <AssignmentDetailPage /> },
      { path: '/teacher/elearning/courses/:courseId/assignments/:assignmentId/submissions', element: <SubmissionsGradingPage /> },
      { path: '/teacher/elearning/courses/:courseId/quizzes/new', element: <QuizBuilderPage /> },
      { path: '/teacher/elearning/courses/:courseId/quizzes/:quizId/builder', element: <QuizBuilderPage /> },
      { path: '/teacher/elearning/courses/:courseId/quizzes/:quizId/results', element: <QuizResultsPage /> },
      { path: '/teacher/elearning/courses/:courseId/quizzes/:quizId/manual-marking', element: <ManualMarkingPage /> },
      { path: '/teacher/elearning/courses/:courseId/engagement', element: <CourseEngagementPage /> },
      { path: '/teacher/elearning/courses/:courseId/communication', element: <CourseCommunicationPage /> },
      { path: '/hod', element: <HodHomePage /> },
      { path: '/hod/approvals', element: <PendingApprovalsPage /> },
      { path: '/hod/approvals/history', element: <ApprovalHistoryPage /> },
      { path: '/hod/approvals/:assessmentId', element: <MarksApprovalReviewPage /> },
      { path: '/hod/department', element: <DepartmentOverviewPage /> },
      { path: '/hod/department/subjects/:subjectId', element: <SubjectDetailPage /> },
      { path: '/hod/teachers', element: <TeacherPerformanceListPage /> },
      { path: '/hod/teachers/:teacherId', element: <TeacherDetailPage /> },
      { path: '/hod/performance', element: <DepartmentAlertsPage /> },
      { path: '/hod/performance/pairings', element: <DepartmentPairingsPage /> },
      { path: '/hod/students/:studentId', element: <HodStudentPerformancePage /> },
      { path: '/hod/interventions', element: <HodInterventionsPage /> },
      { path: '/hod/announcements', element: <HodAnnouncementsPage /> },
      { path: '/hod/announcements/create', element: <CreateHodAnnouncementPage /> },
      { path: '/hod/exports', element: <HodExportsPage /> },
      { path: '/hod/audit', element: <HodAuditPage /> },
      { path: '/hod/elearning', element: <HodElearningOverviewPage /> },
      { path: '/hod/elearning/courses/:courseId', element: <HodCourseDetailPage /> },
      { path: '/aqa', element: <AqaHomePage /> },
      { path: '/aqa/performance', element: <PerformanceCommandCenterPage /> },
      { path: '/aqa/performance/alerts/:id', element: <AqaAlertDetailPage /> },
      { path: '/aqa/performance/pairings', element: <PairingsOverviewPage /> },
      { path: '/aqa/performance/engine', element: <EngineControlPage /> },
      { path: '/aqa/performance/engine/config', element: <EngineConfigPage /> },
      { path: '/aqa/analytics', element: <AcademicAnalyticsPage /> },
      { path: '/aqa/analytics/classes/:classId', element: <AqaClassAnalyticsPage /> },
      { path: '/aqa/students/at-risk', element: <AtRiskStudentsPage /> },
      { path: '/aqa/students/:studentId', element: <AqaStudentProfilePage /> },
      { path: '/aqa/interventions', element: <AqaInterventionsPage /> },
      { path: '/aqa/reports', element: <AqaReportsPage /> },
      { path: '/aqa/announcements', element: <AqaAnnouncementsPage /> },
      { path: '/aqa/announcements/create', element: <CreateAqaAnnouncementPage /> },
      { path: '/aqa/exports', element: <AqaExportsPage /> },
      { path: '/aqa/audit', element: <AqaAuditPage /> },
      { path: '/aqa/elearning', element: <AqaElearningAuditPage /> },
      { path: '/finance', element: <FinanceHomePage /> },
      { path: '/finance/invoices', element: <InvoiceListPage /> },
      { path: '/finance/invoices/generate', element: <GenerateInvoicesPage /> },
      { path: '/finance/invoices/:id', element: <InvoiceDetailPage /> },
      { path: '/finance/payments/cash', element: <RecordCashPaymentPage /> },
      { path: '/finance/payments/bank', element: <RecordBankTransferPage /> },
      { path: '/finance/payments', element: <PaymentListPage /> },
      { path: '/finance/payments/pending', element: <PendingPaymentApprovalsPage /> },
      { path: '/finance/payments/:id', element: <PaymentDetailPage /> },
      { path: '/finance/receipts', element: <ReceiptListPage /> },
      { path: '/finance/receipts/:id', element: <ReceiptDetailPage /> },
      { path: '/finance/fee-categories', element: <FeeCategoriesPage /> },
      { path: '/finance/fee-categories/create', element: <CreateFeeCategoryPage /> },
      { path: '/finance/fee-categories/:id/edit', element: <EditFeeCategoryPage /> },
      { path: '/finance/fee-structures', element: <FeeStructuresPage /> },
      { path: '/finance/fee-structures/matrix', element: <FeeMatrixPage /> },
      { path: '/finance/fee-structures/create', element: <CreateFeeStructurePage /> },
      { path: '/finance/fee-assignments', element: <FeeAssignmentsPage /> },
      { path: '/finance/assets', element: <AssetsListPage /> },
      { path: '/finance/assets/create', element: <CreateAssetPage /> },
      { path: '/finance/assets/:id/edit', element: <EditAssetPage /> },
      { path: '/finance/assets/:id', element: <AssetDetailPage /> },
      { path: '/finance/reports', element: <FinancialReportsPage /> },
      { path: '/finance/reports/collection', element: <CollectionSummaryReportPage /> },
      { path: '/finance/reports/outstanding', element: <OutstandingBalancesReportPage /> },
      { path: '/finance/reports/daily-collections', element: <DailyCollectionsReportPage /> },
      { path: '/finance/reports/fee-defaulters', element: <FeeDefaultersReportPage /> },
      { path: '/finance/audit', element: <FinancialAuditLogPage /> },
      { path: '/finance/exports', element: <FinanceExportsPage /> },
      { path: '/principal', element: <PrincipalHomePage /> },
      { path: '/principal/approvals', element: <MarksFinalApprovalPage /> },
      { path: '/principal/approvals/marks/:assessmentId', element: <PrincipalMarksReviewPage /> },
      { path: '/principal/results/publish', element: <ResultsPublishingPage /> },
      { path: '/principal/report-cards', element: <ReportCardsManagementPage /> },
      { path: '/principal/report-cards/:id', element: <PrincipalReportCardDetailPage /> },
      { path: '/principal/finance', element: <FinanceOversightPage /> },
      { path: '/principal/finance/approvals', element: <PaymentApprovalsPage /> },
      { path: '/principal/finance/approvals/:id', element: <PaymentApprovalDetailPage /> },
      { path: '/principal/finance/invoices', element: <PrincipalInvoiceManagementPage /> },
      { path: '/principal/performance', element: <PrincipalPerformanceOverviewPage /> },
      { path: '/principal/students', element: <PrincipalStudentsPage /> },
      { path: '/principal/students/:studentId', element: <PrincipalStudentProfilePage /> },
      { path: '/principal/discipline', element: <DisciplineOverviewPage /> },
      { path: '/principal/staff', element: <StaffOverviewPage /> },
      { path: '/principal/announcements', element: <PrincipalAnnouncementsPage /> },
      { path: '/principal/announcements/create', element: <CreatePrincipalAnnouncementPage /> },
      { path: '/principal/analytics', element: <PrincipalAnalyticsPage /> },
      { path: '/principal/reports', element: <PrincipalReportsPage /> },
      { path: '/principal/settings/school', element: <SchoolSettingsPage /> },
      { path: '/principal/audit', element: <PrincipalAuditPage /> },
      { path: '/principal/exports', element: <PrincipalExportsPage /> },
      { path: '/principal/elearning', element: <PrincipalElearningPage /> },
      { path: '/admin', element: <AdminHomePage /> },
      { path: '/admin/users', element: <AdminUsersPage /> },
      { path: '/admin/users/create', element: <CreateUserPage /> },
      { path: '/admin/users/:id', element: <UserDetailPage /> },
      { path: '/admin/users/:id/edit', element: <EditUserPage /> },
      { path: '/admin/academic/setup', element: <AcademicSetupHubPage /> },
      { path: '/admin/classes', element: <ClassesPage /> },
      { path: '/admin/classes/:classId', element: <AdminClassDetailPage /> },
      { path: '/admin/subjects', element: <SubjectsPage /> },
      { path: '/admin/subjects/:subjectId', element: <AdminSubjectDetailPage /> },
      { path: '/admin/grading', element: <GradingPage /> },
      { path: '/admin/grading/create', element: <CreateGradingScalePage /> },
      { path: '/admin/assessment-types', element: <AssessmentTypesPage /> },
      { path: '/admin/students', element: <StudentsPage /> },
      { path: '/admin/students/enrol', element: <EnrolStudentPage /> },
      { path: '/admin/students/:id', element: <StudentAdminProfilePage /> },
      { path: '/admin/finance/fee-categories', element: <AdminFeeCategoriesPage /> },
      { path: '/admin/performance/engine', element: <PerformanceEngineAdminPage /> },
      { path: '/admin/notifications/templates', element: <NotificationTemplatesPage /> },
      { path: '/admin/notifications/templates/:id', element: <NotificationTemplateDetailPage /> },
      { path: '/admin/notifications/send', element: <SendManualNotificationPage /> },
      { path: '/admin/notifications/logs', element: <NotificationLogsPage /> },
      { path: '/admin/analytics', element: <AdminAnalyticsPage /> },
      { path: '/admin/reports', element: <AdminReportsPage /> },
      { path: '/admin/reports/:id', element: <AdminReportDetailPage /> },
      { path: '/admin/audit/finance', element: <FinanceAuditAdminPage /> },
      { path: '/admin/audit/system', element: <SystemAuditPage /> },
      { path: '/admin/settings/system', element: <SystemSettingsPage /> },
      { path: '/admin/announcements', element: <AdminAnnouncementsPage /> },
      { path: '/admin/elearning', element: <AdminElearningPage /> },
      { path: '/reports', element: <ReportsHomePage /> },
      { path: '/reports/builder', element: <ReportBuilderPage /> },
      { path: '/reports/jobs', element: <ReportJobsPage /> },
      { path: '/reports/jobs/:id', element: <ReportJobDetailPage /> },
      { path: '/reports/downloads', element: <DownloadCenterPage /> },
      { path: '/reports/scheduled', element: <ScheduledReportsPage /> },
      { path: '/reports/templates', element: <ReportTemplatesPage /> },
      { path: '/reports/audit', element: <ReportAccessAuditPage /> },
      { path: '/academics/marks/bulk', element: <BulkMarksWorkspacePage /> },
      { path: '/academics/marks/bulk/:assessmentId', element: <BulkMarksSheetPage /> },
      { path: '/academics/marks/review/:assessmentId', element: <MarksReviewWorkspacePage /> },
      { path: '/academics/results', element: <ResultsWorkspacePage /> },
      { path: '/academics/results/class/:classId/term/:termId', element: <ClassResultsReviewPage /> },
      { path: '/academics/results/publish', element: <ResultsPublishingSupportPage /> },
      { path: '/academics/report-cards', element: <ReportCardGenerationCenterPage /> },
      { path: '/academics/report-cards/:studentId/:termId', element: <ReportCardPreviewPage /> },
      { path: '/analytics', element: <AnalyticsWorkspacePage /> },
      { path: '/analytics/academic', element: <AcademicAnalyticsOpsPage /> },
      { path: '/analytics/academic/classes/:classId', element: <OpsClassAnalyticsDetailPage /> },
      { path: '/analytics/academic/subjects/:subjectId', element: <SubjectAnalyticsDetailPage /> },
      { path: '/analytics/academic/teachers/:teacherId', element: <TeacherAnalyticsDetailPage /> },
      { path: '/analytics/students', element: <StudentAnalyticsDirectoryPage /> },
      { path: '/analytics/students/:studentId', element: <StudentAnalyticsProfilePage /> },
      { path: '/analytics/finance', element: <FinanceAnalyticsOpsPage /> },
      { path: '/analytics/enrolment', element: <EnrolmentAnalyticsPage /> },
      { path: '/timetables', element: <TimetableWorkspacePage /> },
      { path: '/timetables/classes/:classId', element: <ClassTimetablePage /> },
      { path: '/timetables/teachers/:teacherId', element: <TeacherTimetablePage /> },
      { path: '/timetables/create', element: <CreateTimetableEntryPage /> },
      { path: '/reports/finance/collection-summary', element: <FinanceReportPage type="Collection Summary Report" /> },
      { path: '/reports/finance/daily-collections', element: <FinanceReportPage type="Daily Collections Report" /> },
      { path: '/reports/finance/outstanding-balances', element: <FinanceReportPage type="Outstanding Balances Report" /> },
      { path: '/reports/finance/fee-defaulters', element: <FinanceReportPage type="Fee Defaulters Report" /> },
      { path: '/reports/finance/student-statement/:studentId', element: <StudentStatementReportPage /> },
    ],
  },
  { path: '*', element: <NotFoundPage /> },
]);
