module.exports = {
  apps: [
    {
      name: 'ks-api-gateway',
      cwd: './services/api-gateway',
      script: 'dist/src/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3000 },
    },
    {
      name: 'ks-auth-service',
      cwd: './services/auth-service',
      script: 'dist/src/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3001 },
    },
    {
      name: 'ks-student-service',
      cwd: './services/student-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3002 },
    },
    {
      name: 'ks-academic-service',
      cwd: './services/academic-service',
      script: 'dist/src/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3003 },
    },
    {
      name: 'ks-finance-service',
      cwd: './services/finance-service',
      script: 'dist/src/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3004 },
    },
    {
      name: 'ks-notification-service',
      cwd: './services/notification-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3005 },
    },
    {
      name: 'ks-analytics-service',
      cwd: './services/analytics-service',
      script: 'dist/src/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3006 },
    },
    {
      name: 'ks-elearning-service',
      cwd: './services/elearning-service',
      script: 'dist/src/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3007 },
    },
  ],
};
