module.exports = {
  apps: [
    {
      name: 'kilimanjaro-gateway',
      cwd: './services/api-gateway',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3000 },
    },
    {
      name: 'kilimanjaro-auth',
      cwd: './services/auth-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3001 },
    },
    {
      name: 'kilimanjaro-student',
      cwd: './services/student-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3002 },
    },
    {
      name: 'kilimanjaro-academic',
      cwd: './services/academic-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3003 },
    },
    {
      name: 'kilimanjaro-finance',
      cwd: './services/finance-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3004 },
    },
    {
      name: 'kilimanjaro-notification',
      cwd: './services/notification-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3005 },
    },
    {
      name: 'kilimanjaro-analytics',
      cwd: './services/analytics-service',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      env: { NODE_ENV: 'production', PORT: 3006 },
    },
  ],
};
