export const ROLES = {
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  BOARD_DIRECTOR: 'BOARD_DIRECTOR',
  MANAGING_DIRECTOR: 'MANAGING_DIRECTOR',
  PRINCIPAL: 'PRINCIPAL',
  ACADEMIC_QA: 'ACADEMIC_QA',
  FINANCE: 'FINANCE',
  HEAD_OF_DEPARTMENT: 'HEAD_OF_DEPARTMENT',
  TEACHER: 'TEACHER',
  PARENT: 'PARENT',
  STUDENT: 'STUDENT',
} as const;
