export const routes = {
  landing: '/',
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  authCallback: '/auth/callback',
  status: '/status',
  app: '/app',
  profile: '/app/profile',
  settings: '/app/settings',
  security: '/app/security',
  notifications: '/app/notifications',
  announcements: '/app/announcements',
  search: '/app/search',
  help: '/app/help',
  about: '/app/about',
  forbidden: '/app/403',
  notFound: '/app/404',
  error: '/app/error',
} as const;
