export const elCourses = [
  {
    id: 'course-form3a-math',
    subjectName: 'Mathematics',
    className: 'Form 3A',
    classSubjectId: 'CS-MATH-F3A',
    term: 'Term 2',
    academicYear: '2026',
    teacherName: 'Rose Mhina',
    status: 'ACTIVE',
    emoji: 'M',
    enrolledCount: 42,
    lessonCount: 8,
    publishedLessons: 6,
    materialCount: 18,
    assignmentCount: 4,
    quizCount: 3,
    completion: 74,
    pendingSubmissions: 12,
    manualMarks: 9,
    inactiveStudents: 5,
    health: 86,
  },
  {
    id: 'course-form2a-physics',
    subjectName: 'Physics',
    className: 'Form 2A',
    classSubjectId: 'CS-PHY-F2A',
    term: 'Term 2',
    academicYear: '2026',
    teacherName: 'Rose Mhina',
    status: 'ACTIVE',
    emoji: 'P',
    enrolledCount: 38,
    lessonCount: 6,
    publishedLessons: 5,
    materialCount: 14,
    assignmentCount: 3,
    quizCount: 2,
    completion: 69,
    pendingSubmissions: 8,
    manualMarks: 4,
    inactiveStudents: 3,
    health: 78,
  },
  {
    id: 'course-form3b-math',
    subjectName: 'Mathematics',
    className: 'Form 3B',
    classSubjectId: 'CS-MATH-F3B',
    term: 'Term 2',
    academicYear: '2026',
    teacherName: 'Rose Mhina',
    status: 'DRAFT',
    emoji: 'D',
    enrolledCount: 40,
    lessonCount: 5,
    publishedLessons: 2,
    materialCount: 9,
    assignmentCount: 2,
    quizCount: 1,
    completion: 42,
    pendingSubmissions: 0,
    manualMarks: 0,
    inactiveStudents: 12,
    health: 52,
  },
];

export const elLessons = [
  {
    id: 'lesson-linear',
    title: 'Linear Equations',
    week: 4,
    topic: 'Algebra foundations',
    status: 'PUBLISHED',
    materials: 4,
    assignments: 1,
    quizzes: 1,
    discussions: 3,
    minutes: 45,
    progress: 84,
    readiness: ['Text note published', 'Worksheet downloadable', 'Quiz answer key verified'],
  },
  {
    id: 'lesson-graphs',
    title: 'Graphs and Gradients',
    week: 5,
    topic: 'Coordinate geometry',
    status: 'PUBLISHED',
    materials: 3,
    assignments: 1,
    quizzes: 1,
    discussions: 1,
    minutes: 40,
    progress: 68,
    readiness: ['Video link reviewed', 'Homework published'],
  },
  {
    id: 'lesson-quadratic',
    title: 'Quadratic Foundations',
    week: 6,
    topic: 'Algebra extension',
    status: 'DRAFT',
    materials: 2,
    assignments: 1,
    quizzes: 0,
    discussions: 0,
    minutes: 55,
    progress: 20,
    readiness: ['Missing quiz', 'Text note still draft'],
  },
];

export const elMaterials = [
  {
    id: 'mat-note-linear',
    lessonId: 'lesson-linear',
    title: 'Linear equations text note',
    type: 'NOTE',
    status: 'PUBLISHED',
    body: 'Move constants to one side, then divide by the coefficient of x. Always show both operations.',
    views: 39,
    downloads: 28,
    size: 'Text first',
    lowBandwidth: true,
  },
  {
    id: 'mat-pdf-linear',
    lessonId: 'lesson-linear',
    title: 'Worksheet PDF',
    type: 'PDF',
    status: 'PUBLISHED',
    body: 'Practice worksheet for class and homework.',
    views: 31,
    downloads: 24,
    size: '420 KB',
    lowBandwidth: true,
  },
  {
    id: 'mat-video-graphs',
    lessonId: 'lesson-graphs',
    title: 'Gradient worked example',
    type: 'VIDEO',
    status: 'DRAFT',
    body: 'Short video link explaining gradient from two points.',
    views: 0,
    downloads: 0,
    size: 'External link',
    lowBandwidth: false,
  },
];

export const elAssignments = [
  {
    id: 'assign-1',
    title: 'Linear equation worksheet',
    due: 'Tomorrow 16:00',
    mode: 'Text or file',
    maxScore: 20,
    submitted: 30,
    missing: 12,
    late: 2,
    returned: 1,
    status: 'PUBLISHED',
    instructions: 'Solve all questions and show working. Type answers or upload a clear photo.',
  },
  {
    id: 'assign-2',
    title: 'Graph interpretation task',
    due: 'Friday 15:00',
    mode: 'Text',
    maxScore: 15,
    submitted: 21,
    missing: 21,
    late: 0,
    returned: 0,
    status: 'PUBLISHED',
    instructions: 'Explain the gradient and intercepts for each graph.',
  },
  {
    id: 'assign-3',
    title: 'Quadratic practice',
    due: 'Next Monday',
    mode: 'File',
    maxScore: 25,
    submitted: 0,
    missing: 42,
    late: 0,
    returned: 0,
    status: 'DRAFT',
    instructions: 'Upload full written workings after class review.',
  },
];

export const elSubmissions = [
  {
    id: 'sub-1',
    student: 'Amina Baraka Juma',
    status: 'SUBMITTED',
    submittedAt: 'Today 08:12',
    score: null,
    maxScore: 20,
    text: 'Question 1: x = 3. I moved 4 to the right side then divided by 2.',
    file: 'amina-linear-workings.jpg',
    late: false,
  },
  {
    id: 'sub-2',
    student: 'Jabir Hassan',
    status: 'GRADED',
    submittedAt: 'Yesterday 20:04',
    score: 16,
    maxScore: 20,
    text: 'All answers completed. I need help with question 8.',
    file: null,
    late: false,
  },
  {
    id: 'sub-3',
    student: 'Zahara Mushi',
    status: 'LATE',
    submittedAt: '2 days late',
    score: null,
    maxScore: 20,
    text: 'Late submission due to illness. Work attached.',
    file: 'zahara-worksheet.pdf',
    late: true,
  },
];

export const elMissingStudents = [
  { student: 'Brian Mwangi', lastActive: '3 days ago', reason: 'No submission' },
  { student: 'Neema Said', lastActive: 'Yesterday', reason: 'Draft saved only' },
  { student: 'Juma Omari', lastActive: 'Never opened assignment', reason: 'Missing' },
];

export const elQuestions = [
  {
    id: 'q1',
    type: 'MULTIPLE_CHOICE',
    prompt: 'Solve: 2x + 4 = 12',
    points: 2,
    correct: 'x = 4',
    explanation: 'Subtract 4 from both sides, then divide by 2.',
    options: ['x = 3', 'x = 4', 'x = 5'],
  },
  {
    id: 'q2',
    type: 'TRUE_FALSE',
    prompt: 'A straight-line graph has constant gradient.',
    points: 1,
    correct: 'True',
    explanation: 'The gradient does not change along a straight line.',
    options: ['True', 'False'],
  },
  {
    id: 'q3',
    type: 'SHORT_ANSWER',
    prompt: 'Explain what a gradient represents.',
    points: 4,
    correct: 'Rate of change or steepness of a line.',
    explanation: 'Award points for rate of change, vertical change, horizontal change, and context.',
    options: [],
  },
];

export const elQuizAttempts = [
  { id: 'att-1', student: 'Amina Baraka Juma', score: 88, status: 'AUTO_GRADED', attempt: 1, manualPending: 0, time: '8m 24s' },
  { id: 'att-2', student: 'Jabir Hassan', score: 47, status: 'MANUAL_PENDING', attempt: 1, manualPending: 2, time: '12m 00s' },
  { id: 'att-3', student: 'Zahara Mushi', score: 72, status: 'AUTO_GRADED', attempt: 2, manualPending: 0, time: '10m 15s' },
];

export const elStudents = [
  { name: 'Amina Baraka Juma', completion: 92, materials: 18, assignments: 4, quizzes: 3, activity: 'Viewed 3 materials today', risk: 'LOW' },
  { name: 'Jabir Hassan', completion: 38, materials: 6, assignments: 1, quizzes: 1, activity: 'Missed Quiz 2', risk: 'HIGH' },
  { name: 'Zahara Mushi', completion: 64, materials: 12, assignments: 3, quizzes: 2, activity: 'Assignment submitted late', risk: 'MEDIUM' },
  { name: 'Brian Mwangi', completion: 81, materials: 16, assignments: 3, quizzes: 3, activity: 'Completed lesson 5', risk: 'LOW' },
];

export const elAnnouncements = [
  { id: 'ann-1', title: 'Revision clinic tomorrow', status: 'PUBLISHED', pinned: true, audience: 'Students and parents' },
  { id: 'ann-2', title: 'Quiz 2 opens Friday', status: 'DRAFT', pinned: false, audience: 'Students only' },
];

export const elDiscussions = [
  { id: 'disc-1', title: 'When do I divide both sides?', lesson: 'Linear Equations', replies: 2, status: 'OPEN', author: 'Amina' },
  { id: 'disc-2', title: 'Can I submit a photo?', lesson: 'Linear Equations', replies: 1, status: 'RESOLVED', author: 'Jabir' },
];

export const elAuditLogs = [
  { action: 'QUIZ_PUBLISHED', actor: 'Rose Mhina', target: 'Linear Equations Quiz', time: 'Today 09:14' },
  { action: 'SUBMISSION_GRADED', actor: 'Rose Mhina', target: 'Jabir Hassan', time: 'Yesterday 18:22' },
  { action: 'LOCAL_FILE_UPLOADED', actor: 'Rose Mhina', target: 'Worksheet PDF', time: 'Yesterday 11:05' },
];
