import { Body, Controller, Delete, Get, HttpCode, HttpStatus, Logger, Param, Patch, Post, Query } from '@nestjs/common';
import { ApiTags } from '@nestjs/swagger';
import { ROLES } from '../common/constants/roles';
import { Roles } from '../common/decorators/roles.decorator';
import { CurrentUser } from '../common/decorators/current-user.decorator';
import { RequestUser } from '../common/interfaces/request-user.interface';
import { TimetableService, CreateVenueDto, CreateTimetableActivityDto, CreateSheetDto, CreateSlotDto, AutoGenerateDto } from './timetable.service';

const ALL_STAFF = [ROLES.SYSTEM_ADMIN, ROLES.PRINCIPAL, ROLES.MANAGER, ROLES.HEAD_OF_SCHOOL, ROLES.SUPER_ADMIN, ROLES.ACADEMIC_QA, ROLES.HEAD_OF_DEPARTMENT, ROLES.TEACHER];
const ADMIN_ROLES = [ROLES.SYSTEM_ADMIN, ROLES.PRINCIPAL, ROLES.MANAGER, ROLES.HEAD_OF_SCHOOL, ROLES.SUPER_ADMIN, ROLES.ACADEMIC_QA];

@ApiTags('Academic - Timetable')
@Controller('academics')
export class TimetableController {
  private readonly logger = new Logger(TimetableController.name);
  constructor(private readonly timetableService: TimetableService) {}

  // ── Venues ────────────────────────────────────────────────────────────────

  @Post('venues')
  @Roles(...ADMIN_ROLES)
  createVenue(@Body() dto: CreateVenueDto) {
    return this.timetableService.createVenue(dto);
  }

  @Get('venues')
  @Roles(...ALL_STAFF)
  listVenues(@Query('type') type?: string, @Query('stage') stage?: string, @Query('isActive') isActive?: string) {
    return this.timetableService.listVenues({ type, stage, isActive });
  }

  @Patch('venues/:id')
  @Roles(...ADMIN_ROLES)
  updateVenue(@Param('id') id: string, @Body() dto: Partial<CreateVenueDto> & { isActive?: boolean }) {
    return this.timetableService.updateVenue(id, dto);
  }

  @Delete('venues/:id')
  @Roles(...ADMIN_ROLES)
  @HttpCode(HttpStatus.NO_CONTENT)
  deleteVenue(@Param('id') id: string) {
    return this.timetableService.deleteVenue(id);
  }

  // ── Activities ────────────────────────────────────────────────────────────

  @Post('timetable-activities')
  @Roles(...ADMIN_ROLES)
  createActivity(@Body() dto: CreateTimetableActivityDto) {
    return this.timetableService.createActivity(dto);
  }

  @Get('timetable-activities')
  @Roles(...ALL_STAFF)
  listActivities(@Query('type') type?: string, @Query('stage') stage?: string, @Query('isActive') isActive?: string) {
    return this.timetableService.listActivities({ type, stage, isActive });
  }

  @Patch('timetable-activities/:id')
  @Roles(...ADMIN_ROLES)
  updateActivity(@Param('id') id: string, @Body() dto: Partial<CreateTimetableActivityDto> & { isActive?: boolean }) {
    return this.timetableService.updateActivity(id, dto);
  }

  @Delete('timetable-activities/:id')
  @Roles(...ADMIN_ROLES)
  @HttpCode(HttpStatus.NO_CONTENT)
  deleteActivity(@Param('id') id: string) {
    return this.timetableService.deleteActivity(id);
  }

  // ── Timetable Sheets ──────────────────────────────────────────────────────

  @Post('timetable-sheets')
  @Roles(...ADMIN_ROLES)
  createSheet(@Body() dto: CreateSheetDto, @CurrentUser() user?: RequestUser) {
    return this.timetableService.createSheet(dto, user);
  }

  @Get('timetable-sheets')
  @Roles(...ALL_STAFF, ROLES.STUDENT)
  listSheets(
    @Query('timetableType') timetableType?: string,
    @Query('stage') stage?: string,
    @Query('academicYearId') academicYearId?: string,
    @Query('termId') termId?: string,
    @Query('classId') classId?: string,
    @CurrentUser() user?: RequestUser,
  ) {
    return this.timetableService.listSheets({ timetableType, stage, academicYearId, termId, classId }, user);
  }

  @Get('timetable-sheets/:id')
  @Roles(...ALL_STAFF, ROLES.STUDENT)
  getSheet(@Param('id') id: string, @CurrentUser() user?: RequestUser) {
    return this.timetableService.getSheet(id, user);
  }

  @Patch('timetable-sheets/:id')
  @Roles(...ADMIN_ROLES)
  updateSheet(@Param('id') id: string, @Body() dto: Partial<CreateSheetDto> & { isPublished?: boolean }, @CurrentUser() user?: RequestUser) {
    return this.timetableService.updateSheet(id, dto, user);
  }

  @Delete('timetable-sheets/:id')
  @Roles(...ADMIN_ROLES)
  @HttpCode(HttpStatus.NO_CONTENT)
  deleteSheet(@Param('id') id: string, @CurrentUser() user?: RequestUser) {
    return this.timetableService.deleteSheet(id, user);
  }

  // ── Timetable Slots ───────────────────────────────────────────────────────

  @Post('timetable-slots')
  @Roles(...ADMIN_ROLES)
  createSlot(@Body() dto: CreateSlotDto, @CurrentUser() user?: RequestUser) {
    return this.timetableService.createSlot(dto, user);
  }

  @Patch('timetable-slots/:id')
  @Roles(...ADMIN_ROLES)
  updateSlot(@Param('id') id: string, @Body() dto: Partial<CreateSlotDto>, @CurrentUser() user?: RequestUser) {
    return this.timetableService.updateSlot(id, dto, user);
  }

  @Delete('timetable-slots/:id')
  @Roles(...ADMIN_ROLES)
  @HttpCode(HttpStatus.NO_CONTENT)
  deleteSlot(@Param('id') id: string, @CurrentUser() user?: RequestUser) {
    return this.timetableService.deleteSlot(id, user);
  }

  // ── Conflict Check ────────────────────────────────────────────────────────

  @Post('timetable-slots/check-conflicts')
  @Roles(...ADMIN_ROLES)
  checkConflicts(@Body() dto: Partial<CreateSlotDto> & { excludeSlotId?: string }) {
    return this.timetableService.checkConflicts(dto);
  }

  // ── Auto-Generate ─────────────────────────────────────────────────────────

  @Post('timetable-sheets/:id/auto-generate')
  @Roles(...ADMIN_ROLES)
  autoGenerate(@Param('id') id: string, @Body() dto: Omit<AutoGenerateDto, 'sheetId'>, @CurrentUser() user?: RequestUser) {
    return this.timetableService.autoGenerate({ ...dto, sheetId: id }, user);
  }

  // ── Legacy (deprecated) ───────────────────────────────────────────────────
  // These endpoints write to the old flat Timetable model.
  // Migrate callers to /timetable-sheets and /timetable-slots.

  /** @deprecated Use POST /academics/timetable-sheets + /timetable-slots */
  @Post('timetables')
  @Roles(...ADMIN_ROLES)
  create(@Body() dto: any) {
    this.logger.warn('POST /academics/timetables is deprecated — migrate to /timetable-sheets');
    return this.timetableService.create(dto);
  }

  /** @deprecated Use GET /academics/timetable-sheets */
  @Get('timetables')
  @Roles(...ALL_STAFF, ROLES.STUDENT)
  list(
    @Query('classId') classId?: string,
    @Query('termId') termId?: string,
    @Query('teacherId') teacherId?: string,
    @Query('dayOfWeek') dayOfWeek?: string,
  ) {
    this.logger.warn('GET /academics/timetables is deprecated — migrate to /timetable-sheets');
    return this.timetableService.list({ classId, termId, teacherId, dayOfWeek });
  }

  /** @deprecated Use DELETE /academics/timetable-slots/:id */
  @Delete('timetables/:id')
  @Roles(...ADMIN_ROLES)
  remove(@Param('id') id: string) {
    this.logger.warn('DELETE /academics/timetables/:id is deprecated — migrate to /timetable-slots/:id');
    return this.timetableService.delete(id);
  }
}
