import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

// ─── DTOs (inline for single-file simplicity) ─────────────────────────────────

export interface CreateVenueDto {
  name: string;
  type?: string;
  capacity?: number;
  stageFilter?: string[];
  description?: string;
}

export interface CreateTimetableActivityDto {
  name: string;
  activityType?: string;
  defaultDuration?: number;
  stageFilter?: string[];
  description?: string;
  colorCode?: string;
}

export interface CreateSheetDto {
  name: string;
  timetableType?: string;
  stage?: string;
  classId?: string;
  className?: string;
  academicYearId: string;
  termId?: string;
  note?: string;
}

export interface CreateSlotDto {
  sheetId: string;
  dayOfWeek: string;
  startTime: string;
  endTime: string;
  activityType?: string;
  label?: string;
  activityId?: string;
  subjectId?: string;
  subjectName?: string;
  teacherId?: string;
  teacherName?: string;
  classId?: string;
  className?: string;
  venueId?: string;
  combinationId?: string;
  attendeeIds?: string[];
  staffIds?: string[];
  staffNames?: string[];
  notes?: string;
  colorCode?: string;
}

export interface AutoGenerateDto {
  sheetId: string;
  classSubjects?: Array<{
    subjectId: string;
    subjectName: string;
    teacherId: string;
    teacherName: string;
    periodsPerWeek: number;
  }>;
  periodDurationMinutes?: number;
  periodDuration?: number;         // frontend alias
  schoolDayStartTime?: string;
  startTime?: string;              // frontend alias
  breakAfterPeriod?: number;
  breakAfterPeriods?: number;      // frontend alias
  breakDurationMinutes?: number;
  breakDuration?: number;          // frontend alias
  venueId?: string;
}

@Injectable()
export class TimetableService {
  constructor(private readonly prisma: PrismaService) {}

  // ── Venues ────────────────────────────────────────────────────────────────

  async createVenue(dto: CreateVenueDto) {
    return this.prisma.venue.create({ data: {
      name: dto.name,
      type: dto.type as any ?? 'CLASSROOM',
      capacity: dto.capacity ?? 40,
      stageFilter: dto.stageFilter ?? [],
      description: dto.description,
    }});
  }

  async listVenues(filters: { type?: string; stage?: string; isActive?: string }) {
    return this.prisma.venue.findMany({
      where: {
        type: filters.type as any,
        isActive: filters.isActive === undefined ? undefined : filters.isActive === 'true',
        ...(filters.stage ? { stageFilter: { has: filters.stage } } : {}),
      },
      orderBy: [{ type: 'asc' }, { name: 'asc' }],
    });
  }

  async updateVenue(id: string, dto: Partial<CreateVenueDto> & { isActive?: boolean }) {
    const existing = await this.prisma.venue.findUnique({ where: { id } });
    if (!existing) throw new NotFoundException('Venue not found');
    return this.prisma.venue.update({ where: { id }, data: {
      name: dto.name,
      type: dto.type as any,
      capacity: dto.capacity,
      stageFilter: dto.stageFilter,
      description: dto.description,
      isActive: dto.isActive,
    }});
  }

  async deleteVenue(id: string) {
    const existing = await this.prisma.venue.findUnique({ where: { id } });
    if (!existing) throw new NotFoundException('Venue not found');
    const slotCount = await this.prisma.timetableSlot.count({ where: { venueId: id } });
    if (slotCount > 0) {
      throw new BadRequestException(`Cannot delete "${existing.name}" — it is used in ${slotCount} timetable slot${slotCount > 1 ? 's' : ''}. Remove those slots first.`);
    }
    return this.prisma.venue.delete({ where: { id } });
  }

  // ── Activities ────────────────────────────────────────────────────────────

  async createActivity(dto: CreateTimetableActivityDto) {
    return this.prisma.timetableActivity.create({ data: {
      name: dto.name,
      activityType: dto.activityType as any ?? 'LESSON',
      defaultDuration: dto.defaultDuration ?? 40,
      stageFilter: dto.stageFilter ?? [],
      description: dto.description,
      colorCode: dto.colorCode ?? '#4338CA',
    }});
  }

  async listActivities(filters: { type?: string; stage?: string; isActive?: string }) {
    return this.prisma.timetableActivity.findMany({
      where: {
        activityType: filters.type as any,
        isActive: filters.isActive === undefined ? undefined : filters.isActive === 'true',
        ...(filters.stage ? { stageFilter: { has: filters.stage } } : {}),
      },
      orderBy: [{ activityType: 'asc' }, { name: 'asc' }],
    });
  }

  async updateActivity(id: string, dto: Partial<CreateTimetableActivityDto> & { isActive?: boolean }) {
    const existing = await this.prisma.timetableActivity.findUnique({ where: { id } });
    if (!existing) throw new NotFoundException('Activity not found');
    return this.prisma.timetableActivity.update({ where: { id }, data: {
      name: dto.name,
      activityType: dto.activityType as any,
      defaultDuration: dto.defaultDuration,
      stageFilter: dto.stageFilter,
      description: dto.description,
      colorCode: dto.colorCode,
      isActive: dto.isActive,
    }});
  }

  async deleteActivity(id: string) {
    const existing = await this.prisma.timetableActivity.findUnique({ where: { id } });
    if (!existing) throw new NotFoundException('Activity not found');
    const slotCount = await this.prisma.timetableSlot.count({ where: { activityId: id } });
    if (slotCount > 0) {
      throw new BadRequestException(`Cannot delete "${existing.name}" — it is used in ${slotCount} timetable slot${slotCount > 1 ? 's' : ''}.`);
    }
    return this.prisma.timetableActivity.delete({ where: { id } });
  }

  // ── Timetable Sheets ──────────────────────────────────────────────────────

  async createSheet(dto: CreateSheetDto) {
    return this.prisma.timetableSheet.create({ data: {
      name: dto.name,
      timetableType: dto.timetableType as any ?? 'CLASS',
      stage: dto.stage,
      classId: dto.classId,
      className: dto.className,
      academicYearId: dto.academicYearId,
      termId: dto.termId,
      note: dto.note,
    }, include: { slots: true }});
  }

  async listSheets(filters: { timetableType?: string; stage?: string; academicYearId?: string; termId?: string; classId?: string }) {
    return this.prisma.timetableSheet.findMany({
      where: {
        timetableType: filters.timetableType as any,
        stage: filters.stage,
        academicYearId: filters.academicYearId,
        termId: filters.termId,
        classId: filters.classId,
      },
      include: { slots: { include: { venue: true, activity: true }, orderBy: [{ dayOfWeek: 'asc' }, { startTime: 'asc' }] } },
      orderBy: [{ timetableType: 'asc' }, { stage: 'asc' }, { name: 'asc' }],
    });
  }

  async getSheet(id: string) {
    const sheet = await this.prisma.timetableSheet.findUnique({
      where: { id },
      include: { slots: { include: { venue: true, activity: true }, orderBy: [{ dayOfWeek: 'asc' }, { startTime: 'asc' }] } },
    });
    if (!sheet) throw new NotFoundException('Timetable not found');
    return sheet;
  }

  async updateSheet(id: string, dto: Partial<CreateSheetDto> & { isPublished?: boolean }) {
    const existing = await this.prisma.timetableSheet.findUnique({ where: { id } });
    if (!existing) throw new NotFoundException('Timetable not found');
    return this.prisma.timetableSheet.update({ where: { id }, data: {
      name: dto.name,
      timetableType: dto.timetableType as any,
      stage: dto.stage,
      classId: dto.classId,
      className: dto.className,
      termId: dto.termId,
      note: dto.note,
      isPublished: dto.isPublished,
    }, include: { slots: { include: { venue: true, activity: true }, orderBy: [{ dayOfWeek: 'asc' }, { startTime: 'asc' }] } }});
  }

  async deleteSheet(id: string) {
    const existing = await this.prisma.timetableSheet.findUnique({ where: { id } });
    if (!existing) throw new NotFoundException('Timetable not found');
    return this.prisma.timetableSheet.delete({ where: { id } });
  }

  // ── Timetable Slots ───────────────────────────────────────────────────────

  async createSlot(dto: CreateSlotDto) {
    await this.assertNoConflicts(dto);
    return this.prisma.timetableSlot.create({
      data: {
        sheetId: dto.sheetId,
        dayOfWeek: dto.dayOfWeek as any,
        startTime: dto.startTime,
        endTime: dto.endTime,
        activityType: dto.activityType as any ?? 'LESSON',
        label: dto.label,
        activityId: dto.activityId,
        subjectId: dto.subjectId,
        subjectName: dto.subjectName,
        teacherId: dto.teacherId,
        teacherName: dto.teacherName,
        classId: dto.classId,
        className: dto.className,
        venueId: dto.venueId,
        combinationId: dto.combinationId,
        attendeeIds: dto.attendeeIds ?? [],
        staffIds: dto.staffIds ?? [],
        staffNames: dto.staffNames ?? [],
        notes: dto.notes,
        colorCode: dto.colorCode,
      },
      include: { venue: true, activity: true },
    });
  }

  async updateSlot(id: string, dto: Partial<CreateSlotDto>) {
    const existing = await this.prisma.timetableSlot.findUnique({ where: { id } });
    if (!existing) throw new NotFoundException('Slot not found');
    const merged = { ...existing, ...dto, sheetId: existing.sheetId };
    await this.assertNoConflicts(merged as any, id);
    return this.prisma.timetableSlot.update({
      where: { id },
      data: {
        dayOfWeek: dto.dayOfWeek as any,
        startTime: dto.startTime,
        endTime: dto.endTime,
        activityType: dto.activityType as any,
        label: dto.label,
        activityId: dto.activityId,
        subjectId: dto.subjectId,
        subjectName: dto.subjectName,
        teacherId: dto.teacherId,
        teacherName: dto.teacherName,
        classId: dto.classId,
        className: dto.className,
        venueId: dto.venueId,
        combinationId: dto.combinationId,
        attendeeIds: dto.attendeeIds,
        staffIds: dto.staffIds,
        staffNames: dto.staffNames,
        notes: dto.notes,
        colorCode: dto.colorCode,
      },
      include: { venue: true, activity: true },
    });
  }

  async deleteSlot(id: string) {
    const existing = await this.prisma.timetableSlot.findUnique({ where: { id } });
    if (!existing) throw new NotFoundException('Slot not found');
    return this.prisma.timetableSlot.delete({ where: { id } });
  }

  // ── Conflict Detection ────────────────────────────────────────────────────

  private timeToMinutes(t: string): number {
    const [h, m] = t.split(':').map(Number);
    return h * 60 + m;
  }

  private overlaps(aStart: string, aEnd: string, bStart: string, bEnd: string): boolean {
    const as = this.timeToMinutes(aStart);
    const ae = this.timeToMinutes(aEnd);
    const bs = this.timeToMinutes(bStart);
    const be = this.timeToMinutes(bEnd);
    return as < be && ae > bs;
  }

  async checkConflicts(dto: Partial<CreateSlotDto> & { excludeSlotId?: string }) {
    const { sheetId, dayOfWeek, startTime, endTime, teacherId, venueId, classId, excludeSlotId } = dto;
    if (!sheetId || !dayOfWeek || !startTime || !endTime) return { conflicts: [] };

    const sheet = await this.prisma.timetableSheet.findUnique({ where: { id: sheetId } });
    if (!sheet) return { conflicts: [] };

    // Get all slots for the same academicYear/termId on the same day that could conflict
    const candidates = await this.prisma.timetableSlot.findMany({
      where: {
        dayOfWeek: dayOfWeek as any,
        id: excludeSlotId ? { not: excludeSlotId } : undefined,
        sheet: { academicYearId: sheet.academicYearId },
      },
      include: { sheet: true },
    });

    const conflicts: Array<{ type: string; message: string; slotId: string; sheetName: string }> = [];

    for (const slot of candidates) {
      if (!this.overlaps(startTime, endTime, slot.startTime, slot.endTime)) continue;
      if (teacherId && slot.teacherId === teacherId) {
        conflicts.push({ type: 'TEACHER', slotId: slot.id, sheetName: (slot.sheet as any).name, message: `${dto.teacherName ?? 'This teacher'} is already scheduled at this time in "${(slot.sheet as any).name}"` });
      }
      if (venueId && slot.venueId === venueId) {
        conflicts.push({ type: 'VENUE', slotId: slot.id, sheetName: (slot.sheet as any).name, message: `This venue is already booked at this time in "${(slot.sheet as any).name}"` });
      }
      if (classId && slot.classId === classId && slot.sheetId === sheetId) {
        conflicts.push({ type: 'CLASS', slotId: slot.id, sheetName: (slot.sheet as any).name, message: `This class already has a slot at this time` });
      }
    }

    return { conflicts };
  }

  private async assertNoConflicts(dto: CreateSlotDto, excludeSlotId?: string) {
    const result = await this.checkConflicts({ ...dto, excludeSlotId });
    if (result.conflicts.length > 0) {
      const messages = result.conflicts.map((c) => c.message).join('; ');
      throw new BadRequestException(`Scheduling conflict: ${messages}`);
    }
  }

  // ── Auto-Generate ─────────────────────────────────────────────────────────

  async autoGenerate(dto: AutoGenerateDto) {
    const sheet = await this.prisma.timetableSheet.findUnique({ where: { id: dto.sheetId } });
    if (!sheet) throw new NotFoundException('Timetable sheet not found');

    // Resolve field name aliases (frontend uses different names than the DTO)
    const duration   = dto.periodDurationMinutes ?? dto.periodDuration ?? 40;
    const startOfDay = dto.schoolDayStartTime    ?? dto.startTime      ?? '07:00';
    const breakAfter = dto.breakAfterPeriod      ?? dto.breakAfterPeriods ?? 3;
    const breakDur   = dto.breakDurationMinutes  ?? dto.breakDuration     ?? 20;

    // Auto-fetch class subjects from DB when not supplied by caller
    type PeriodEntry = { subjectId: string; subjectName: string; teacherId: string; teacherName: string };
    let classSubjects = dto.classSubjects ?? [];

    if (classSubjects.length === 0 && sheet.academicYearId) {
      const where: Record<string, unknown> = { academicYearId: sheet.academicYearId, isActive: true };
      if (sheet.classId) where['classId'] = sheet.classId;
      const dbSubjects = await (this.prisma as any).classSubject.findMany({
        where,
        include: { subject: true },
      });
      classSubjects = dbSubjects.map((cs: any) => ({
        subjectId:      cs.subjectId,
        subjectName:    cs.subject?.name ?? 'Subject',
        teacherId:      cs.teacherId ?? '',
        teacherName:    '',
        periodsPerWeek: 4,
      }));
    }

    if (classSubjects.length === 0) {
      const hint = sheet.classId
        ? 'Go to Subjects → assign subjects to this class first.'
        : 'This timetable sheet has no class assigned. Open sheet settings, set a class, then retry.';
      throw new BadRequestException(`No subjects found to schedule. ${hint}`);
    }

    // Clear existing slots for this sheet first
    await this.prisma.timetableSlot.deleteMany({ where: { sheetId: dto.sheetId } });

    const days: Array<'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY'> = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'];

    // Build full period queue: each subject repeated periodsPerWeek times
    const fullQueue: PeriodEntry[] = [];
    for (const cs of classSubjects) {
      for (let i = 0; i < (cs.periodsPerWeek ?? 4); i++) {
        fullQueue.push({ subjectId: cs.subjectId, subjectName: cs.subjectName, teacherId: cs.teacherId, teacherName: cs.teacherName });
      }
    }

    // Shuffle for variety
    for (let i = fullQueue.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [fullQueue[i], fullQueue[j]] = [fullQueue[j], fullQueue[i]];
    }

    // ── Distribute evenly across days ─────────────────────────────────────────
    // Split queue into 5 roughly equal chunks (one per day) so every day gets lessons
    const periodsPerDay = Math.ceil(fullQueue.length / days.length);

    const slotsToCreate: Omit<CreateSlotDto, 'sheetId'>[] = [];

    for (let di = 0; di < days.length; di++) {
      const day = days[di];
      const daySlice = fullQueue.slice(di * periodsPerDay, (di + 1) * periodsPerDay);
      if (daySlice.length === 0) continue;

      let [startH, startM] = startOfDay.split(':').map(Number);
      let periodCount = 0;

      for (const entry of daySlice) {
        if (startH >= 17) break; // don't schedule past 5 PM

        // Insert break before this period if needed
        if (periodCount > 0 && periodCount % breakAfter === 0) {
          const bStart = `${String(startH).padStart(2, '0')}:${String(startM).padStart(2, '0')}`;
          startM += breakDur;
          if (startM >= 60) { startH += Math.floor(startM / 60); startM %= 60; }
          const bEnd = `${String(startH).padStart(2, '0')}:${String(startM).padStart(2, '0')}`;
          slotsToCreate.push({ dayOfWeek: day, startTime: bStart, endTime: bEnd, activityType: 'BREAK', label: 'Break', colorCode: '#94A3B8', attendeeIds: [], staffIds: [], staffNames: [] });
          if (startH >= 17) break;
        }

        const slotStart = `${String(startH).padStart(2, '0')}:${String(startM).padStart(2, '0')}`;
        startM += duration;
        if (startM >= 60) { startH += Math.floor(startM / 60); startM %= 60; }
        const slotEnd = `${String(startH).padStart(2, '0')}:${String(startM).padStart(2, '0')}`;

        slotsToCreate.push({
          dayOfWeek: day,
          startTime: slotStart,
          endTime: slotEnd,
          activityType: 'LESSON',
          label: entry.subjectName,
          subjectId: entry.subjectId,
          subjectName: entry.subjectName,
          teacherId: entry.teacherId || undefined,
          teacherName: entry.teacherName || undefined,
          classId: sheet.classId ?? undefined,
          className: sheet.className ?? undefined,
          venueId: dto.venueId,
          colorCode: '#4338CA',
          attendeeIds: [],
          staffIds: entry.teacherId ? [entry.teacherId] : [],
          staffNames: entry.teacherName ? [entry.teacherName] : [],
        });

        periodCount++;
      }
    }

    if (slotsToCreate.length === 0) {
      throw new BadRequestException('No slots could be generated. Check that start time is before 17:00 and period duration is valid.');
    }

    // Batch create
    await this.prisma.timetableSlot.createMany({
      data: slotsToCreate.map((s) => ({
        ...s,
        sheetId: dto.sheetId,
        dayOfWeek: s.dayOfWeek as any,
        activityType: s.activityType as any ?? 'LESSON',
      })),
    });

    return this.getSheet(dto.sheetId);
  }

  // ── Legacy (existing Timetable model) ────────────────────────────────────

  create(dto: any) {
    return this.prisma.timetable.create({ data: dto });
  }

  list(filters: { classId?: string; termId?: string; teacherId?: string; dayOfWeek?: string }) {
    return this.prisma.timetable.findMany({
      where: {
        classId: filters.classId,
        termId: filters.termId,
        teacherId: filters.teacherId,
        dayOfWeek: filters.dayOfWeek as any,
      },
      include: { subject: true },
      orderBy: [{ dayOfWeek: 'asc' }, { startTime: 'asc' }],
    });
  }

  delete(id: string) {
    return this.prisma.timetable.delete({ where: { id } });
  }
}
