export const ROLES = {
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  PRINCIPAL: 'PRINCIPAL',
  MANAGER: 'MANAGER',
  HEAD_OF_SCHOOL: 'HEAD_OF_SCHOOL',
  SUPER_ADMIN: 'SUPER_ADMIN',
  HEAD_OF_FINANCE: 'HEAD_OF_FINANCE',
  ACADEMIC_QA: 'ACADEMIC_QA',
  HEAD_OF_DEPARTMENT: 'HEAD_OF_DEPARTMENT',
  TEACHER: 'TEACHER',
  PARENT: 'PARENT',
  STUDENT: 'STUDENT',
  MANAGING_DIRECTOR: 'MANAGING_DIRECTOR',
} as const;
