import '../../models/auth_user.dart';

class ShellRouteSpec {
  const ShellRouteSpec({
    required this.prefix,
    required this.role,
    required this.tab2,
    required this.tab3,
    required this.tab4,
    required this.extras,
  });

  final String prefix;
  final UserRole role;
  final String tab2;
  final String tab3;
  final String tab4;
  final List<String> extras;
}

const shellRouteSpecs = <ShellRouteSpec>[
  ShellRouteSpec(
    prefix: 'student',
    role: UserRole.student,
    tab2: 'results',
    tab3: 'attendance',
    tab4: 'learn',
    extras: [
      'finance',
      'performance-trends',
      'report-cards',
      'announcements',
      'settings',
      'profile',
      'notifications',
      'notification-preferences',
      'about',
      'search',
    ],
  ),
  ShellRouteSpec(
    prefix: 'parent',
    role: UserRole.parent,
    tab2: 'academics',
    tab3: 'finance',
    tab4: 'learning',
    extras: [
      'attendance',
      'performance-alerts',
      'report-cards',
      'announcements',
      'contact-school',
      'children',
      'settings',
      'profile',
      'notifications',
      'notification-preferences',
      'about',
      'search',
    ],
  ),
  ShellRouteSpec(
    prefix: 'teacher',
    role: UserRole.teacher,
    tab2: 'classes',
    tab3: 'courses',
    tab4: 'attendance',
    extras: [
      'marks',
      'performance-alerts',
      'peer-pairings',
      'students',
      'timetable',
      'syllabus-tracker',
      'announcements',
      'settings',
      'profile',
      'notifications',
      'notification-preferences',
      'about',
      'search',
    ],
  ),
  ShellRouteSpec(
    prefix: 'hod',
    role: UserRole.hod,
    tab2: 'approvals',
    tab3: 'department',
    tab4: 'performance',
    extras: [
      'courses',
      'teachers',
      'subject-analytics',
      'interventions',
      'timetable',
      'announcements',
      'settings',
      'profile',
      'notifications',
      'notification-preferences',
      'about',
      'search',
    ],
  ),
  ShellRouteSpec(
    prefix: 'aqa',
    role: UserRole.academicQa,
    tab2: 'performance',
    tab3: 'analytics',
    tab4: 'interventions',
    extras: [
      'classes',
      'teachers',
      'engine-config',
      'reports',
      'announcements',
      'settings',
      'profile',
      'notifications',
      'notification-preferences',
      'about',
      'search',
    ],
  ),
  ShellRouteSpec(
    prefix: 'principal',
    role: UserRole.principal,
    tab2: 'approvals',
    tab3: 'analytics',
    tab4: 'students',
    extras: [
      'finance',
      'performance',
      'discipline',
      'staff',
      'announcements',
      'reports',
      'school-settings',
      'settings',
      'profile',
      'notifications',
      'notification-preferences',
      'about',
      'search',
    ],
  ),
  ShellRouteSpec(
    prefix: 'finance',
    role: UserRole.finance,
    tab2: 'invoices',
    tab3: 'payments',
    tab4: 'reports',
    extras: [
      'fee-categories',
      'fee-structures',
      'fee-assignments',
      'assets',
      'audit',
      'settings',
      'profile',
      'notifications',
      'notification-preferences',
      'about',
      'search',
    ],
  ),
  ShellRouteSpec(
    prefix: 'admin',
    role: UserRole.admin,
    tab2: 'users',
    tab3: 'system',
    tab4: 'notifications',
    extras: [
      'students',
      'classes',
      'subjects',
      'grading-scales',
      'assessment-types',
      'fee-categories',
      'performance-engine',
      'notification-templates',
      'manual-notification',
      'notification-logs',
      'analytics',
      'reports',
      'financial-audit',
      'system-audit',
      'settings',
      'announcements',
      'profile',
      'notifications',
      'notification-preferences',
      'about',
      'search',
    ],
  ),
];
